### ISSUE TITLE
language server crashs when typing json like yaml `{ }`

### ISSUE THREAD

**Issue by ChristopherHX** [microsoft/azure-pipelines-language-server#167]
Version: 1.237.0-pr-574-c4a655e the unreleased update downloaded here https://github.com/microsoft/azure-pipelines-vscode/pull/574 under GitHub Actions

YAML
```yaml
variables:
- template: ./v1.yaml
stages:
- stage:
  variables:
  - template: ./v1.yaml
    parameters:
      test: me
  jobs:
  - job:
    variables:
    - template: ./v1.yaml
      parameters:
        test: me
    # Everything before typing the following line works without crash
    - {  }
``` 

Crash
```
/home/user/.vscode-oss/extensions/ms-azure-devops.azure-pipelines-1.237.0-pr-574-c4a655e/dist/server.js:1981
    return node.key.kind === Yaml.Kind.SCALAR &&
                ^

TypeError: Cannot read properties of undefined (reading 'key')
    at isCompileTimeExpression (/home/user/.vscode-oss/extensions/ms-azure-devops.azure-pipelines-1.237.0-pr-574-c4a655e/dist/server.js:1981:17)
    at addItemsToArrayNode (/home/user/.vscode-oss/extensions/ms-azure-devops.azure-pipelines-1.237.0-pr-574-c4a655e/dist/server.js:1922:48)
    at recursivelyBuildAst (/home/user/.vscode-oss/extensions/ms-azure-devops.azure-pipelines-1.237.0-pr-574-c4a655e/dist/server.js:1833:13)
    at recursivelyBuildAst (/home/user/.vscode-oss/extensions/ms-azure-devops.azure-pipelines-1.237.0-pr-574-c4a655e/dist/server.js:1825:48)
    at addPropertiesToObjectNode (/home/user/.vscode-oss/extensions/ms-azure-devops.azure-pipelines-1.237.0-pr-574-c4a655e/dist/server.js:1900:30)
    at recursivelyBuildAst (/home/user/.vscode-oss/extensions/ms-azure-devops.azure-pipelines-1.237.0-pr-574-c4a655e/dist/server.js:1813:13)
    at addItemsToArrayNode (/home/user/.vscode-oss/extensions/ms-azure-devops.azure-pipelines-1.237.0-pr-574-c4a655e/dist/server.js:1972:28)
    at recursivelyBuildAst (/home/user/.vscode-oss/extensions/ms-azure-devops.azure-pipelines-1.237.0-pr-574-c4a655e/dist/server.js:1833:13)
    at recursivelyBuildAst (/home/user/.vscode-oss/extensions/ms-azure-devops.azure-pipelines-1.237.0-pr-574-c4a655e/dist/server.js:1825:48)
    at addPropertiesToObjectNode (/home/user/.vscode-oss/extensions/ms-azure-devops.azure-pipelines-1.237.0-pr-574-c4a655e/dist/server.js:1900:30)

Node.js v20.9.0
[Error - 17:52:00] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Cannot read properties of undefined (reading 'key')
  Code: -32603 
[Error - 17:52:00] Connection to server got closed. Server will not be restarted.
```
_I wanted to see how intellisense works in that case inside this extension and noticed that the language server has gone away_
